"""Build data/kse100.js for the FINTRA homepage tape.

Source: Pakistan Stock Exchange data portal (dps.psx.com.pk), public endpoints.
Verified reachable without an API key. No CORS header is sent by PSX, so the
browser cannot fetch these directly: this script runs out of band and writes a
same-origin snapshot the page reads.

Run:  python tools/fetch_tape.py
Out:  data/kse100.js  (window.FINTRA_TAPE = {...})
"""
import html
import os
import json
import re
import urllib.request
from datetime import datetime, timezone, timedelta

PKT = timezone(timedelta(hours=5))
UA = {"User-Agent": "Mozilla/5.0 (fintra-site tape snapshot)"}
ROOT = __file__.replace("\\", "/").rsplit("/tools/", 1)[0]


def get(url, timeout=30):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "ignore")


def intraday(limit=180):
    """Index intraday points: [unix_seconds, index_value, volume]."""
    try:
        raw = json.loads(get("https://dps.psx.com.pk/timeseries/int/KSE100"))
    except Exception as exc:  # network, parse, or upstream change
        return [], "intraday unavailable: %s" % exc
    pts = (raw or {}).get("data") or []
    if not pts:
        return [], "intraday returned no points"
    pts = sorted(pts, key=lambda p: p[0])[-limit:]
    return [[int(p[0]), float(p[1]), int(p[2])] for p in pts], ""


def day_change():
    """Previous close from the EOD series (returned newest-first)."""
    try:
        raw = json.loads(get("https://dps.psx.com.pk/timeseries/eod/KSE100"))
    except Exception:
        return None, "eod not json"
    pts = (raw or {}).get("data") or []
    if len(pts) < 2:
        return None, "eod too short"
    pts = sorted(pts, key=lambda p: int(p[0]))
    return float(pts[-2][1]), ""


def market_watch(max_rows=14):
    """Parse the market-watch table. Values come from data-order attributes,
    which is where PSX puts the unformatted number, so no rounding guesswork."""
    try:
        page = get("https://dps.psx.com.pk/market-watch")
    except Exception as exc:
        return [], "market-watch unavailable: %s" % exc
    rows = []
    for tr in re.findall(r"<tr.*?</tr>", page, re.S):
        sym = re.search(r'data-search="([^"]+)"', tr)
        if not sym:
            continue
        name = re.search(r'data-title="([^"]+)"', tr)
        listed = re.search(r"<td>(ALLSHR[^<]*)</td>", tr)
        nums = []
        for v in re.findall(r'data-order="([^"]+)"', tr):
            try:
                nums.append(float(v))
            except ValueError:
                continue
        if len(nums) < 8:
            continue
        ldcp, _open, _high, _low, last, chg, chg_pct, vol = nums[:8]
        rows.append({
            "sym": sym.group(1),
            "name": html.unescape(name.group(1)) if name else "",
            "last": last,
            "chg": round(chg, 2),
            "chg_pct": round(chg_pct, 2),
            "vol": int(vol),
            "kse100": "KSE100" in (listed.group(1) if listed else "").upper(),
        })
    rows.sort(key=lambda r: r["vol"], reverse=True)
    return rows[:max_rows], ""


def main():
    series, err_series = intraday()
    prev_close, err_eod = day_change()
    watch, err_watch = market_watch()

    if not series:
        payload = {"as_of": None, "error": err_series or "no data"}
    else:
        last = series[-1][1]
        first = series[0][1]
        values = [p[1] for p in series]
        day_high, day_low = max(values), min(values)
        base = prev_close if prev_close else first
        basis = "prev close" if prev_close else "session open"
        payload = {
            "as_of": datetime.fromtimestamp(series[-1][0], PKT).isoformat(timespec="minutes"),
            "built_at": datetime.now(PKT).isoformat(timespec="minutes"),
            "index": {
                "name": "KSE-100",
                "last": last,
                "base": base,
                "basis": basis,
                "chg": round(last - base, 2),
                "chg_pct": round((last - base) / base * 100, 2) if base else None,
                "high": day_high,
                "low": day_low,
                "session_volume": sum(p[2] for p in series),
                "series": [[p[0], p[1]] for p in series],
                "volume_series": [[p[0], p[2]] for p in series][-60:],
            },
            "watch": watch,
            "watched_rows": len(watch),
            "notes": [n for n in (err_series, err_eod, err_watch) if n],
        }

    out = "%s/data/kse100.js" % ROOT
    os.makedirs("%s/data" % ROOT, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/fetch_tape.py. Source: dps.psx.com.pk public endpoints.\n")
        f.write("// Re-run to refresh; the static site reads this snapshot (no CORS on PSX).\n")
        f.write("window.FINTRA_TAPE = %s;\n" % json.dumps(payload, separators=(",", ":")))
    print("wrote", out)
    print(json.dumps({k: v for k, v in payload.items() if k not in ("index", "watch")}, indent=1))
    if "index" in payload:
        i = payload["index"]
        print("index:", i["last"], "vs", i["basis"], i["base"], "->", i["chg"], "(%s%%)" % i["chg_pct"],
              "| points:", len(i["series"]), "| high/low:", i["high"], i["low"])
    print("watch rows:", payload.get("watched_rows"))
    for r in payload.get("watch", [])[:6]:
        print("  ", r["sym"], r["last"], r["chg"], "%s%%" % r["chg_pct"], r["vol"], "KSE100" if r["kse100"] else "")


if __name__ == "__main__":
    main()
